version: 2

sources:
  - name: raw           # The name you want to give to the dataset
    schema : gz_raw_data         # schema is the name of the dataset in BigQuery
    description: The raw dataset
    tables:
      - name: sales              # name you want to give the table
        identifier: raw_gz_sales     # identifier is the name of the table in BigQuery
        description: has quantity, revenue and date for each product. Multiple products by order_id
        freshness: 
          warn_after: {count : 90, period : day}
        loaded_at_field: 'CAST(date_date AS TIMESTAMP)'
        columns:
          - name: pdt_id || '-' || orders_id   
            tests:
              - unique
              - not_null
                  

      - name : product
        identifier: raw_gz_product
        description: has only product_id and its price
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
                  
                  

      - name : ship
        identifier: raw_gz_ship
        description: has orders_id and its log cost and ship cost
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
      
      
      - name: adwords
        identifier: raw_gz_adwords


      - name: facebook
        identifier: raw_gz_facebook


      - name: criteo
        identifier: raw_gz_criteo

      - name: bing
        identifier: raw_gz_bing 


models:

  - name : int_sales_margin
    tests:
      - unique:
          column_name: "(orders_id || '-' || pdt_id)"
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - Purchase_cost
            - date_date
            - revenue
            - quantity

  # - name: finance_campaigns_day
  #   description: global kpi
  #   columns:
  #     - name: ads_margin
  #       description: operational_margin - ads_cost
  #       tests:
  #         - not_null
  #     - name: average_basket
  #       description: average basket cost for each day
  #       tests:
  #         - not_null

# models:
#   - name: int_campaigns
#     description: all campaign data
#     tests:
#       - unique:
#           column_name :  "(campaign_key || '-' || date_date)"