version: 2

sources:
  - name: raw           # The alias you want to give to the dataset (used in DBT)
    schema : gz_raw_data         # schema is the name of the dataset in BigQuery
    description: The raw dataset
    tables:
      - name: sales              # alias you want to give the table (used in DBT)
        identifier: raw_gz_sales     # identifier is the name of the table in BigQuery
        description: has quantity, revenue and date for each product. Multiple products by order_id
        tests:
          - dbt_utils.unique_combination_of_columns:
              combination_of_columns:
                - month
                - products
              
                  

      - name : product
        identifier: raw_gz_product
        description: has only product_id and its price
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
                  
                  

      - name : ship
        identifier: raw_gz_ship
        description: has orders_id and its log cost and ship cost
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null

      
      - name: adwords
        identifier: raw_gz_adwords


      - name: facebook
        identifier: raw_gz_facebook


      - name: criteo
        identifier: raw_gz_criteo

      - name: bing
        identifier: raw_gz_bing 


